<?php
/**
 * Copyright © Bruno Pelaquin. All rights reserved.
 * https://github.com/https-pelaquin
 * https://www.linkedin.com/in/bruno-pelaquin/
 */

/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$width = (int)$block->getWidth();
$height = (int)$block->getHeight();
$paddingBottom = $block->getRatio() * 100;
$sliderImageUrls = (array)$block->getData('slider_image_urls');
$sliderImageUrls = array_values(array_unique([(string)$block->getImageUrl(), ...$sliderImageUrls]));
?>

<span class="product-image-container product-image-container-<?= /* @noEscape */ $block->getProductId() ?>">
    <span class="product-image-wrapper bp-product-slider-image"
          data-mage-init='{"Pelaquin_HoverImageProductGrids/js/product-slider": {}}'>
        <?php foreach ($sliderImageUrls as $index => $imageUrl): ?>
            <img class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
                <?php if ($index === 0): ?>
                    <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                        <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtmlAttr($value) ?>"
                    <?php endforeach; ?>
                <?php endif; ?>
                src="<?= $escaper->escapeUrl($imageUrl) ?>"
                loading="lazy"
                width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
                height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
                alt="<?= $index === 0 ? $escaper->escapeHtmlAttr($block->getLabel()) : '' ?>"
                <?php if ($index !== 0): ?>
                    aria-hidden="true"
                <?php endif; ?> />
        <?php endforeach; ?>
    </span>
</span>
<?php
$styles = <<<STYLE
.product-image-container-{$block->getProductId()} {
    width: {$width}px;
    height: auto;
    aspect-ratio: {$width} / {$height};
}
.product-image-container-{$block->getProductId()} span.product-image-wrapper {
    height: 100%;
    width: 100%;
}
@supports not (aspect-ratio: auto) {
    .product-image-container-{$block->getProductId()} span.product-image-wrapper {
        padding-bottom: {$paddingBottom}%;
    }
}
STYLE;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], $styles, false) ?>
